// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package transactions_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// TransactionsServiceClient is the client API for TransactionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionsServiceClient interface {
	RawRecordsWithCredentials(ctx context.Context, in *CredentialsRawRecordsRequest, opts ...grpc.CallOption) (*RawRecordsResponse, error)
	RawRecordsFromBytes(ctx context.Context, in *BytesRawRecordsRequest, opts ...grpc.CallOption) (*RawRecordsResponse, error)
}

type transactionsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionsServiceClient(cc grpc.ClientConnInterface) TransactionsServiceClient {
	return &transactionsServiceClient{cc}
}

func (c *transactionsServiceClient) RawRecordsWithCredentials(ctx context.Context, in *CredentialsRawRecordsRequest, opts ...grpc.CallOption) (*RawRecordsResponse, error) {
	out := new(RawRecordsResponse)
	err := c.cc.Invoke(ctx, "/transactions.TransactionsService/RawRecordsWithCredentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionsServiceClient) RawRecordsFromBytes(ctx context.Context, in *BytesRawRecordsRequest, opts ...grpc.CallOption) (*RawRecordsResponse, error) {
	out := new(RawRecordsResponse)
	err := c.cc.Invoke(ctx, "/transactions.TransactionsService/RawRecordsFromBytes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionsServiceServer is the server API for TransactionsService service.
// All implementations must embed UnimplementedTransactionsServiceServer
// for forward compatibility
type TransactionsServiceServer interface {
	RawRecordsWithCredentials(context.Context, *CredentialsRawRecordsRequest) (*RawRecordsResponse, error)
	RawRecordsFromBytes(context.Context, *BytesRawRecordsRequest) (*RawRecordsResponse, error)
	mustEmbedUnimplementedTransactionsServiceServer()
}

// UnimplementedTransactionsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTransactionsServiceServer struct {
}

func (UnimplementedTransactionsServiceServer) RawRecordsWithCredentials(context.Context, *CredentialsRawRecordsRequest) (*RawRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawRecordsWithCredentials not implemented")
}
func (UnimplementedTransactionsServiceServer) RawRecordsFromBytes(context.Context, *BytesRawRecordsRequest) (*RawRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawRecordsFromBytes not implemented")
}
func (UnimplementedTransactionsServiceServer) mustEmbedUnimplementedTransactionsServiceServer() {}

// UnsafeTransactionsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionsServiceServer will
// result in compilation errors.
type UnsafeTransactionsServiceServer interface {
	mustEmbedUnimplementedTransactionsServiceServer()
}

func RegisterTransactionsServiceServer(s *grpc.Server, srv TransactionsServiceServer) {
	s.RegisterService(&_TransactionsService_serviceDesc, srv)
}

func _TransactionsService_RawRecordsWithCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialsRawRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionsServiceServer).RawRecordsWithCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transactions.TransactionsService/RawRecordsWithCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionsServiceServer).RawRecordsWithCredentials(ctx, req.(*CredentialsRawRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionsService_RawRecordsFromBytes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BytesRawRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionsServiceServer).RawRecordsFromBytes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transactions.TransactionsService/RawRecordsFromBytes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionsServiceServer).RawRecordsFromBytes(ctx, req.(*BytesRawRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TransactionsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "transactions.TransactionsService",
	HandlerType: (*TransactionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RawRecordsWithCredentials",
			Handler:    _TransactionsService_RawRecordsWithCredentials_Handler,
		},
		{
			MethodName: "RawRecordsFromBytes",
			Handler:    _TransactionsService_RawRecordsFromBytes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transactions_service.proto",
}
